### ISSUE TITLE
如何打开有密码的文档？

### ISSUE THREAD

**Issue by ZCHWorld** [sky8650/TbsForOffice#1]
请问老兄有没研究过怎么用tbs打开有密码的文档呢？我APP也是老兄这种做法，并不会提示输入密码，直接加载失败。我另外也测试过微信、QQ、QQ邮箱。微信和QQ邮件可以，但它使用的是“Android SDK（完整版 + 文件能力）”这个SDK；QQ里不行，和我们一样用“Android SDK（完整版）”这个SDK。

我尝试了一下“Android SDK（完整版 + 文件能力）”，没能成功打开有密码的文件，并且有个比较大的缺点就是你没法完全控制页面，这个页面完全是QQ浏览器团队的，含有很多下载链接，很容易就下一个QQ浏览器。。。比较头痛

**Comment by sky8650** [comment]
可不可以这样： 把加密的文件下载到本地，然后自行解密（不依赖于tbs），然后用tbs只打开解密后的文件。   阅读完之后删除解密后的文件

**Comment by sky8650** [comment]
可不可以这样： 把加密的文件下载到本地，然后自行解密（不依赖于tbs），再用tbs只打开解密后的文件。 阅读完之后删除解密后的文件
