### ISSUE TITLE
9.0的系统初始化内核就失败了

### ISSUE THREAD

**Issue by FrankLove** [sky8650/TbsForOffice#5]
测试了小米和华为9.0的手机，内核初始化都失败了。换了官方最新的sdk还是一样，官方文档说一句支持9.0了，为什么还是初始化内核失败

**Comment by sky8650** [comment]
查找一下失败的提示是什么，或者查一下你的码设置的是否正确

**Comment by FrankLove** [comment]
@sky8650 用的是你的demo，并且初始化代码就一句话。同样的demo在7.0上初始化成功,在9.0一直失败。你那边测试9.0上正常吗

**Comment by sky8650** [comment]
我这正常哦

**Comment by sky8650** [comment]
> 测试了小米和华为9.0的手机，内核初始化都失败了。换了官方最新的sdk还是一样，官方文档说一句支持9.0了，为什么还是初始化内核失败 我这正常哦

**Comment by FrankLove** [comment]
@sky8650 你用的是什么机型和android版本测试的，我这台华为荣耀8a,微信扫码都显示000000,本机微信都没有加载成功x5内核

**Comment by FrankLove** [comment]
@sky8650 问题解决了，请问你有试过在一个页面连续打开不同的文件吗，我这边测试发现打开第二个文件就一直显示加载中

**Comment by sky8650** [comment]
没有试过这种场景

**Comment by FrankLove** [comment]
@sky8650 问题解决了，如果想要在一个页面内不断打开不同的文件需要重新实例化对象，还要移除再重新添加到view里面

**Comment by sky8650** [comment]
你那个9.0的手机内核初始化失败是怎么解决的？

**Comment by FrankLove** [comment]
@sky8650 一开始用你的demo,由于下载内核需要申请存储权限，但是你的demo没有做动态权限申请，导致打开demo需要手动配置权限。手动配置完之后无论怎么操作都无法触发内核下载了。于是修改动态权限申请然后就可以下载内核了。

**Comment by sky8650** [comment]
嗯，好的，一开始也想到这个问题了。  那内核的初始化不就不能放在application中，需要放在申请权限之后吧

**Comment by FrankLove** [comment]
可以放在application里面，但是需要保证运行的第一个页面就有权限申请处理，弹出权限申请这个过程，application里面的代码还不会执行。不然应该就不能放在application里面，具体还没测试过

**Comment by sky8650** [comment]
嗯，明白，谢谢
